Recommend Us page
openlibhums/hourglass pull request #403
Opened 2024-10-25 08:51 UTC by joemull

Reliant on https://github.com/openlibhums/consortial_billing/pull/81.

When complete, will close https://github.com/openlibhums/consortial_billing/issues/74.

2024-10-29 11:18 UTC, ajrbyers requested changes
Generally this works well. I did notice that there was a lack of spacing when there is more than one article returned by a search though.

<img width="591" alt="Screenshot 2024-10-29 at 11 10 50" src="https://github.com/user-attachments/assets/aef35fac-cee1-4160-9354-e90e3ab4c29f">

2024-10-29 17:56 UTC, mauromsl approved these changes

2024-10-29 17:57 UTC, ajrbyers requested changes

2024-10-29 17:57 UTC, ajrbyers commented on templates/custom/recommend-us.html
> +      {#{% include 'custom/astrolabe-opener.html' %}#}
Is this commented out?

2024-10-30 14:44 UTC, joemull commented on templates/custom/recommend-us.html
> +      {#{% include 'custom/astrolabe-opener.html' %}#}
Yeah that's where the artwork would be pulled in but haven't decided on what to use yet. I might uncomment / complete the artwork as a separate PR along with Rose's copyedits

2024-10-31 08:18 UTC, ajrbyers approved these changes

2024-10-31 08:18 UTC, merged